### ISSUE TITLE
1.19.2 server failing to start

### ISSUE THREAD

**Issue by AngelWing314** [TheDeathlyCow/frostiful#62] opened 2024-01-19 09:35 UTC
My 19.2. server is failing to start. One of the errors in logs mention forstiful

[10:23:37] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'edenring'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.6.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.6.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:25) [fabric-loader-0.15.6.jar:?]
        Suppressed: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                at me.shedaniel.autoconfig.util.Utils.constructUnsafely(Utils.java:49) ~[cloth-config-8.3.115-fabric.jar:?]
                at me.shedaniel.autoconfig.serializer.GsonConfigSerializer.createDefault(GsonConfigSerializer.java:92) ~[cloth-config-8.3.115-fabric.jar:?]
                at me.shedaniel.autoconfig.serializer.GsonConfigSerializer.deserialize(GsonConfigSerializer.java:86) ~[cloth-config-8.3.115-fabric.jar:?]
                at me.shedaniel.autoconfig.ConfigManager.load(ConfigManager.java:92) ~[cloth-config-8.3.115-fabric.jar:?]
                at me.shedaniel.autoconfig.ConfigManager.<init>(ConfigManager.java:53) ~[cloth-config-8.3.115-fabric.jar:?]
                at me.shedaniel.autoconfig.AutoConfig.register(AutoConfig.java:66) ~[cloth-config-8.3.115-fabric.jar:?]
                at com.github.thedeathlycow.frostiful.init.Frostiful.onInitialize(Frostiful.java:44) ~[frostiful-0.5.7.jar:?]
                at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.6.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.6.jar:?]
                at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.6.jar:?]
                at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.6.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.6.jar:?]
                at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.6.jar:?]
                at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:25) [fabric-loader-0.15.6.jar:?]
        Caused by: java.lang.reflect.InvocationTargetException
                at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
                at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
                at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
                at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
                at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
                at me.shedaniel.autoconfig.util.Utils.constructUnsafely(Utils.java:47) ~[cloth-config-8.3.115-fabric.jar:?]
                ... 14 more
        Caused by: java.lang.NoSuchFieldError: clientConfig
                at com.github.thedeathlycow.frostiful.config.FrostifulConfig.<init>(FrostifulConfig.java:15) ~[frostiful-0.5.7.jar:?]
                at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
                at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
                at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
                at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
                at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
                at me.shedaniel.autoconfig.util.Utils.constructUnsafely(Utils.java:47) ~[cloth-config-8.3.115-fabric.jar:?]
                ... 14 more
Caused by: java.lang.NoSuchFieldError: COLORS
        at paulevs.edenring.blocks.VolvoxBlock.<clinit>(VolvoxBlock.java:84) ~[eden-ring-0.6.4.jar:?]
        at paulevs.edenring.registries.EdenBlocks.<clinit>(EdenBlocks.java:129) ~[eden-ring-0.6.4.jar:?]
        at paulevs.edenring.EdenRing.onInitialize(EdenRing.java:52) ~[eden-ring-0.6.4.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.6.jar:?]
        ... 7 more

**Comment by NerjalNosk** [comment] 2024-01-19 10:06
This is not caused by Frostiful, but by Eden Ring.
You should try updatung it or report that issue to them.
(Also, better provide a _full_ crash log, this here most definitely isn't enough to properly fix a bug)

**Comment by TheDeathlyCow** [comment] 2024-01-19 10:12
Use fabric loader 0.14. This issue was fixed in 1.20.

**Closed by TheDeathlyCow** 2024-01-19 10:12 UTC

**Comment by TheDeathlyCow** [comment] 2024-04-13 13:43
fixed for 1.19.2: https://modrinth.com/mod/frostiful/version/0.5.8
