### ISSUE TITLE
Incompatibility with Lucky Blocks mod

### ISSUE THREAD

**Issue by Zano1999** [TheDeathlyCow/frostiful#39] opened 2023-07-10 18:30 UTC
With your mod installed and the Lucky Blocks mod the game crash on startup

Log: https://pastebin.com/wLnC2jMU
Crash report: https://pastebin.com/GKc1ksHq

**Comment by TheDeathlyCow** [comment] 2023-07-11 05:35
Do you have a link to the mod? I found this but the id seems to be different: https://modrinth.com/mod/luckyblocks

**Comment by TheDeathlyCow** [comment] 2023-07-11 06:45
Actually, I think I found it [here](https://www.luckyblockmod.com/download/lucky-block-fabric/1.19.2-13.0/). The problem is on Lucky Block's side, not mine. They attempt to execute a switch statement over the `EnchantmentTarget` class and throw `NoWhenBranchMatchedException` when the default branch is reached in the method `FabricGameAPIKt#toEnchantmentType`. This exception is unhandled and thus causes a crash. Unfortunately due to the rather poor way that Minecraft implemented `EnchantmentTarget`, in order to add my own custom target (which I do for the Frost Wand) I have to do some weird ASM stuff to extend the enum. Since this extension is not included in their switch statement, it will always fallback to the default branch and cause a crash. There isn't much I can do to fix this (without removing a feature from the mod), so I would suggest contacting the Lucky Block developer.

**Comment by TheDeathlyCow** [comment] 2024-01-25 02:33
reopening because this can be fixed in 1.20.5

**Comment by TheDeathlyCow** [comment] 2024-04-23 14:29
Ok for some reason that old link got bought out by some dodgy crypto bros. I think this might be the same mod but since its still 1.20.2 I cant test yet: https://www.curseforge.com/minecraft/mc-mods/lucky-block

**Closed** 2024-04-26 08:45 UTC
Labels: compatibility
